### ISSUE TITLE
Oreexcavation can excavate with any tool

### ISSUE THREAD

**Issue by icyrane** [ChosenArchitect/Bounds-1.12-Modpack#100]
Reported on the server by ItzPuggyPlayz#6914, tested it out on my side. If you open the oreexcavationmod config, ignore tool is set to true by default (e.g. you can excavate anything with any tool). Switching it to false however does not remove the functionality (even after switching it to false I can still massacre trees with the quest book).

Probably an issue related to the mod itself, but it's worth mentioning it here.

**Comment by TGSRagnarok** [comment]
It's a bug with the mod itself enigmatica  2 has the same issue
