### ISSUE TITLE
Quest not letting me pass

### ISSUE THREAD

**Issue by Cazzelrey** [ChosenArchitect/Bounds-1.12-Modpack#102]
I have done the quest Age of Wood Tier 1: Basic Mechanical Power. But it wont say complete and let me go on to the next quest. I did not go to the nether. But I found nether rack and I nether like place when I was mining. So that is how I got nether rack. All the tasks say COMPLETE. I even constructed a windmill and ran it into a mill stone. Can someone please help me get passed this quest?

**Comment by DeadpoolDE** [comment]
The quest "Age of Wood Tier 1" has a second part. With the right arrow you can see the second part. For the second part of the quest, you need to go to the nether.
