### ISSUE TITLE
Better With Mods Compatibility/Duplication Issue

### ISSUE THREAD

**Issue by Soulmatts** [ChosenArchitect/Bounds-1.12-Modpack#107]
![minecraft bounds glitch](https://user-images.githubusercontent.com/42629365/44501229-bd597e00-a6cf-11e8-9ef4-19ee82a158e3.PNG) 
well I had some logs and an iron axe and I put them in simple storage network crafting area then shift clicked to get the planks and it gave me lots of axes and the right amount of planks.

**Comment by ChosenArchitect** [comment]
This is a bug with Simple Storage Networks.

**Comment by ChosenArchitect** [comment]
Reported to mod dev https://github.com/PrinceOfAmber/Storage-Network/issues/102

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!
