### ISSUE TITLE
Witches do not drop what JEI says they should

### ISSUE THREAD

**Issue by Artira421** [ChosenArchitect/Bounds-1.12-Modpack#108]
JEI shows that witches should drop magic powder, sticks, spell scrolls, bottles, glowstone, gunpowder, redstone, spider eyes, and sugar. However, after killing hundreds they have only dropped magic powder, sticks, bottles, potions, and spell scrolls.

**Comment by ChosenArchitect** [comment]
It should tell you the percentage chance that the other items will drop and they are really low in comparison to the others. Nothing really requires you to kill witches in this pack.
