### ISSUE TITLE
No JEI Recipe for Firework Rocket

### ISSUE THREAD

**Issue by lhdev** [ChosenArchitect/Bounds-1.12-Modpack#11]
As the title says, no recipe to create fireworks.  Have not tested to see if vanilla recipe works.

**Comment by lhdev** [comment]
I realize the vanilla recipe exists, since the recipe book is gone, JEI should have it.

**Comment by ChosenArchitect** [comment]
This is an issue for Jei. Its missing from the list but I added the rockets. The stars can be crafted but there are so many options that I can add them all.
