### ISSUE TITLE
Can't complete "Furnace" quest

### ISSUE THREAD

**Issue by SolReaper** [ChosenArchitect/Bounds-1.12-Modpack#110]
I'm unable to complete the "Furnace" quest, under the "Getting Started" chapter.  I have the stone, not cobblestone and the furnace in my inventory, but the "Claim" and "Detect/Submit" buttons are greyed out. I am running the latest version of the modpack. See attached screenshot,
![mc bounds furnace quest](https://user-images.githubusercontent.com/42703494/44622449-8083b780-a886-11e8-8252-4842e0b295fe.JPG)

**Comment by Ryex** [comment]
to my knowledge, this would typically indicate that the quest IS complete and claimed. what with both goals completed and the claim grayed out. the node in the book is red and not blue or green?

**Comment by alexsch01** [comment]
Did you try clicking on 8 Apples or 8 Seeds or 1 Beetroot Seeds and see if the claim button can be clicked on? It is called choice reward for a reason

**Comment by SolReaper** [comment]
@alpal01 FML!!! I clearly need more caffeine when I play. Thank you for pointing that out to me, I will try that here shortly! :-)
