### ISSUE TITLE
PC Crashed during gameplay, Questbook is empty

### ISSUE THREAD

**Issue by Dublin2274** [ChosenArchitect/Bounds-1.12-Modpack#111]
Title says it all. My PC crashed in the middle of a game. I didnt lose map progress but i went to my quest book and all the quests were gone. It was back to the original minecraft splash screen and the quests are a blank page with an edit button. Any way to reload quests into game and then manually admin complete the ones i had completed?

**Comment by ChosenArchitect** [comment]
Tre redownloading the pack and moving over your save.

**Comment by Dublin2274** [comment]
No that didn't fix it. I did find a solution for it though. I was able to create a new save and take the better questing files from the new one and move them to my current save. What is the command to like admin complete the ones i have completed?

**Comment by rujuk** [comment]
/bq_admin complete <quest_id> [username|uuid]
or you can use the ingame editor
/bq_admin edit
and open questbook then edit, but be careful. its a powerful tool.
or you can give your self the items the quest want you to make and it will detect them and mark for complete.
