### ISSUE TITLE
Iron Hoe And Hemp

### ISSUE THREAD

**Issue by OLine57** [ChosenArchitect/Bounds-1.12-Modpack#114]
When standing in the middle of a crop of fully grown hemp and holding an iron hoe, right-clicking will promptly crash the game.

**Comment by ChosenArchitect** [comment]
Can you pastbin the crash log you get?

**Comment by OLine57** [comment]
Sorry, was on a cruise.  Here's the crash log.

https://pastebin.com/ihFXmWpc

**Comment by ChosenArchitect** [comment]
It's being caused from https://minecraft.curseforge.com/projects/augmented-interactions You can disable the mod and that should fix the issue. The mod has caused more issues then good. I will be removing it in 2.9

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!
