### ISSUE TITLE
Fortune Enchanted Book not Craftable Again

### ISSUE THREAD

**Issue by Artira421** [ChosenArchitect/Bounds-1.12-Modpack#116]
The fortune enchanted book can not be crafted in an anvil. When searched it will not show up in JEI but it can be seen as needed to craft Looting and you can see the recipe using for fortune by clicking the fortune book needed for looting. The recipe requires a book and 16 lapis in an anvil along with "err" levels of exp. Attempting to craft results in a book with blue text that is not enchanted.

**Comment by rujuk** [comment]
recipe still missing form JEI, but you can still find recipe as @Artira421 wrote. But i have no problem making it.
