### ISSUE TITLE
Spelling mistakes in the tips

### ISSUE THREAD

**Issue by DelfCo** [ChosenArchitect/Bounds-1.12-Modpack#117]
I'm talking about the tips that randomly show up while a world is loading.

The tip about Journeymap spells the name of the mod wrong. (This might be old news, I haven't seen that tip in a couple weeks.)
The tip that displays the version of Minecraft you're using misspells "usiing". (Just saw this one today, Sept. 3.)

**Comment by DelfCo** [comment]
Another: tip number 40: Pouring water on still lava *creates* obsidian. The final 's' in 'creates' is missing from the current text.

**Comment by ChosenArchitect** [comment]
Fixed! Thanks for the issue!
