### ISSUE TITLE
Bounce boots quest not recognizing my bounce boots

### ISSUE THREAD

**Issue by DelfCo** [ChosenArchitect/Bounds-1.12-Modpack#119]
I've made three pairs of boots, and even when I click the Detect/Submit button, no joy. It's not blocking my quest progression, which might be why no one has mentioned it yet. Are we sure that the quest is properly set up?

**Comment by ChosenArchitect** [comment]
Fixed in the next update. The mod the boots are from updated and broke the items meta data
