### ISSUE TITLE
Rocket pants don't work in 2.8

### ISSUE THREAD

**Issue by DelfCo** [ChosenArchitect/Bounds-1.12-Modpack#120]
I've got them on, I've got gunpowder in my inventory, and I'm using a mapped key that's not showing any conflicts in the config screen.

I know that the mod in question changed some IDs around, and I'm wondering if, in the process, they somehow disconnected the action code from the pants ID or something.

**Comment by ChosenArchitect** [comment]
They are still working for me. You may need to change the hotkey. Try the V key because that's the key I'm using and its working.

**Comment by DelfCo** [comment]
I've changed the hotkey. I'd changed it to V when I first used them, so I changed it to something else, changed it back, no joy. Made new ones, in case it was an upgrade incompatibility. Still no joy. I'm working on getting by without them, but having no real way to fly in modded is a pain. The glider is a lot less useful without them. 

But apparently, this is just me. Closing.

**Comment by rujuk** [comment]
I had no problem until i made and equipped the goggles. then the rocket jump stopped working when you stand on ground. But if i press the assigned key while jump with goggles & pants equipped i can rocket jump. and you can even hold down the rocket jump key to fly even higher.

**Comment by DelfCo** [comment]
Thanks, I'll try that!

**Comment by DelfCo** [comment]
Eeew. With flight goggles and rocket pants, and Rocket Jump set to V key with no conflicts, a tap on the V key on the ground does nothing. Used to launch me high in the air. Tap on the V key while already in the air launches me up a block or two -- used to do nothing. Holding the V key while in the air keeps moving me higher and higher as long as I hold the key down -- not sure if this used to work like this, never tried it explicitly. The goggles no longer make me float down slowly, I just fall. RIP me, testing this without the bounce boots or a glider.

Reopening this as a potential bug to be reported in Dungeon Tactics, unless there was an inadvertent config change in Bounds that caused it.

**Comment by rujuk** [comment]
I didnt make the flight goggles until r2.8 so i dont know if they should give you slowfall, but according to the book from dungeon tactics they should give you ability to control your fall by burning gunpowder not consume it at once. And that is how i use it.
For the pants only equipped i have no problem launching my self up by pressing the assigned key with no conflicing keybind.
I was wondering if you have tried to make a test world using the latest release and see if problem persists.
im currently playing on new world created with r2.7 updated to latest release.

(sorry if what i wrote makes no sense, my english is not great).

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!
