### ISSUE TITLE
Pulvus & Furnus item duplication through simple storage

### ISSUE THREAD

**Issue by rujuk** [ChosenArchitect/Bounds-1.12-Modpack#122]
I automated my pulvus & furnus using simple storage cables. Any item that can be imported/exported can be duplicated by manually taking the item out through storage request cable or storage remote. Item stays in pulvus/furnus and you get dup item

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!

**Comment by rujuk** [comment]
Problem not fixed, still can duplicate.
