### ISSUE TITLE
Filtered hopper soul sand recipe broken

### ISSUE THREAD

**Issue by bsayer** [ChosenArchitect/Bounds-1.12-Modpack#123]
Steps to reproduce:

1. Power a filtered hopper
2. Insert soul sand in filter slot
3. Drop sand on top
4. Observe that sand sits on top and soul sand is not returned

**Comment by ChosenArchitect** [comment]
This is a bug and ill report

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!
