### ISSUE TITLE
2.9 Server Pack Issues

### ISSUE THREAD

**Issue by TheRadicalDuck** [ChosenArchitect/Bounds-1.12-Modpack#124]
I downloaded and setup the 2.9 server pack, and when I try to join I am met with the following error.

![javaw_2018-09-27_22-20-10](https://user-images.githubusercontent.com/43660732/46184417-99c3bd80-c2a3-11e8-9274-661c825ff417.png)

What might need to be done to fix this issue?

**Comment by ChosenArchitect** [comment]
Will be fixed in the next update.

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!
