### ISSUE TITLE
Better with Mods - HCFishing problem

### ISSUE THREAD

**Issue by Terpo** [ChosenArchitect/Bounds-1.12-Modpack#125]
I am trying to fish but currently I have no such luck.

The book of Better with Mods tells to bait the fishing rod. Also it tells that open sky and three blocks of deep water is needed. I tried it serveral times without any luck. My river has clear sky and is at least 5 blocks deep. 

So I am really out of ideas how to get fish.

**Comment by ChosenArchitect** [comment]
Should Be fixed in 3.0 Will Reopen if the issue comes back up!

**Comment by rujuk** [comment]
Its a BWM thing, the aim is to fish with dynamite. It can take really long time before you get a catch with baited fishing rod. But now we have vanilla fishing. Im happy about that tbh. :+1:
