### ISSUE TITLE
Planting Nether Warts

### ISSUE THREAD

**Issue by rujuk** [ChosenArchitect/Bounds-1.12-Modpack#126]
Havent done alchemy until r3.0, how do i plant/grow nether warts? Vanilla method does not work, when i try to plant they return to my inventory but invisible until i put another item in the slot they are in then they appair again.

**Comment by alexsch01** [comment]
it sounds like a client desync try closing and reopening the world again

**Comment by rujuk** [comment]
i slept on it, it was the planter i totally forgot about. I can plant without problems on it. Maybe BWM thing that you cant plant vanilla method, anyways, thanks for the reply.
