### ISSUE TITLE
Ender tanks crashing a chunk

### ISSUE THREAD

**Issue by SmolderingMinion** [ChosenArchitect/Bounds-1.12-Modpack#128]
on a server i picked up a endertank with shift right click and placed it back down where it originally was and i started crashing over and over and anyone who walked into the chunk would crash over and over. The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException.
The tank was removed in mc edit and the chunk is fine now.

**Comment by ChosenArchitect** [comment]
Added it to the do not pick up list from carry on mod
