### ISSUE TITLE
All Typos

### ISSUE THREAD

**Issue by Austratae** [ChosenArchitect/Bounds-1.12-Modpack#13]
"... make torches and **_may_** other things." Presume this is meant to say "Many".
![quest typo](https://user-images.githubusercontent.com/41763151/43293272-3321d364-90ee-11e8-987d-65f5f8c97a03.JPG)

**Comment by Austratae** [comment]
Drying Basin quest says "Daying Basin"

**Comment by ChosenArchitect** [comment]
Fixed all questlines and spell checked.
