### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Arttie** [ChosenArchitect/Bounds-1.12-Modpack#134]
There is the crashlog. I start it, and never get to the main menu. The load screen gets to about 5/7.

https://pastebin.com/wx24t78A

**Comment by rujuk** [comment]
Are you running clean install or did you manually update forge? My instance of this pack is running forge 14.23.4.2760 and have no issues loading and running.

I tried the version that you are running (14.23.5.2770) and got exact same crash as you got.
