### ISSUE TITLE
[3.0] antique atlas biomes don't match

### ISSUE THREAD

**Issue by soraphis** [ChosenArchitect/Bounds-1.12-Modpack#144]
The biomes for antique atlas don't match.
since the F3 menu does not show the biome ID i can't do much about it

![grafik](https://user-images.githubusercontent.com/3066582/53701189-cc498780-3dfa-11e9-90a7-089718ffca03.png)
*the antique map says i'm in a desert while i'm clearly not*

**Comment by ChosenArchitect** [comment]
In the guest book, I show the item you need to see your location.

**Comment by soraphis** [comment]
the point is: i can't get the biome IDs because the F3 screen is reduced, so I can't change the the antique atlas config to map the biomes correctly. I don't care about the name of the biome I'm in.... i can see in which biome I am, but the map of the antique atlas is simply wrong, as long as the config is not updated
