### ISSUE TITLE
Better Foliage Error

### ISSUE THREAD

**Issue by Austratae** [ChosenArchitect/Bounds-1.12-Modpack#15]
![rip air](https://user-images.githubusercontent.com/41763151/43298197-d9f9c618-9109-11e8-91f9-0b2f9f9ec968.JPG)

**Comment by Austratae** [comment]
DarkLotus just said that he disables it on the server, not sure if that's causing the issue.

**Comment by ChosenArchitect** [comment]
I will have to look more into it. Is it spamming your chat or is it just every now and aging? I haven't had it pop up while testing and I have been testing for around 80+ hrs.

**Comment by Austratae** [comment]
It was just once.

**Comment by lhdev** [comment]
It's not disabled on the server, it's disabled client side, it's purely cosmetic and client side only.  Technically the server isn't even using or loading it.

**Comment by ChosenArchitect** [comment]
I may remove that mod because it's a heavy GPU hitter
