### ISSUE TITLE
Step Assist forced with Iron Armor?

### ISSUE THREAD

**Issue by lhdev** [ChosenArchitect/Bounds-1.12-Modpack#17]
I can't find any options to disable step assist, seems to be forced on when wearing iron armor.
Maybe this is intentional, but it seems like it should be optional.

**Comment by lhdev** [comment]
Ohh, I see that it's a random bonus added to my boots, still, I don't want to recraft boots to not have step assist.

**Comment by ChosenArchitect** [comment]
This is now removed and is an option in your key binds.
