### ISSUE TITLE
Quest suggestion 

### ISSUE THREAD

**Issue by Vanillacraft2002** [ChosenArchitect/Bounds-1.12-Modpack#2]
https://gyazo.com/d3efc6753e88c11223683799b00574df
https://gyazo.com/68aa770f99bd0d8799c3641503c6c34b
iron is needed in 2 different quests maybe remove iron from one of the quests and lock progression with out completion of the other

**Comment by ChosenArchitect** [comment]
Quest was removed in ver 1.1
