### ISSUE TITLE
Boats are slower than swimming

### ISSUE THREAD

**Issue by homerAttack** [ChosenArchitect/Bounds-1.12-Modpack#26]
move slower in a boat than not in a boat

**Comment by ChosenArchitect** [comment]
hcboating {
        # Registry name for entities which are considered boats
        S:"Boat List" <
            minecraft:boat
         >

        # Make boat recipe require a wooden shovel for the oars
        B:"Boat Requires Oar"=false

        # Enables custom recipes provided by this feature
        B:"Custom Recipes"=false

        # Speed modifier when not holding any sail type item
        I:"Default Speed modifier"=50

        # Items which speed up a boat when held, value is a percentage of the vanilla speed
        S:"Speed Items" <
            betterwithmods:material:11=100
            minecraft:banner:*=100

**Comment by ChosenArchitect** [comment]
Will change
