### ISSUE TITLE
Chest Recipe

### ISSUE THREAD

**Issue by lhdev** [ChosenArchitect/Bounds-1.12-Modpack#27]
Can you oredict the plants and slabs so we can use any wood to make chests?  Seems unnecessarily restrictive to just use oak.

**Comment by ChosenArchitect** [comment]
The olive, ironwood, and fir have been added to oak items. Other tree types have their own chests.
![2018-07-28_19 08 19](https://user-images.githubusercontent.com/35053440/43361642-d8b98cf2-9299-11e8-8736-80d563de4c55.png)

**Comment by lhdev** [comment]
Perfect!
