### ISSUE TITLE
Unlimited Mushroom Stew

### ISSUE THREAD

**Issue by Austratae** [ChosenArchitect/Bounds-1.12-Modpack#28]
Got a free mushroom stew from a food bag. Have been eating from it ever since, and it still hasn't ran out. Have eaten it a good 10 times, at least, and have received four bowls from it, but it still remains in my inventory and edible. Just like the corn chowder bug.

**Comment by lhdev** [comment]
Seems maybe the simple corn mod can be added back once the unlimited bowl food thing is resolved.
