### ISSUE TITLE
Firework recipe

### ISSUE THREAD

**Issue by Balphazar** [ChosenArchitect/Bounds-1.12-Modpack#31]
The fireworks have 2 recipes for some reason. one requires 3 gunpowder and a paper for 3 fireworks the other requires 2 gunpowder and a paper for 3 fireworks 
![firework png](https://user-images.githubusercontent.com/41807361/43369557-ad7ce2e6-933e-11e8-9206-5f7de51026df.jpg)

**Comment by ChosenArchitect** [comment]
That's how fireworks work. There are 3 lvs  https://www.digminecraft.com/firework_recipes/make_firework_rocket.php
