### ISSUE TITLE
Quest Mispelling or....   +  Nature's Compass Quest Not Recognizing item

### ISSUE THREAD

**Issue by alpal01** [ChosenArchitect/Bounds-1.12-Modpack#41]
For the Spelunking, Stone Level quest description it says you can upgrade to new tetra or vanilla tools but I think you mean gilded tools/jewelled tools

**Comment by alpal01** [comment]
And natures compass quest under mapping doesn't want to be checked off even though I have item in inventory

**Comment by jellonek** [comment]
I can confirm - it's not detecting an item. Tested with item without any NBT data set yet. Dropping and getting it back also does not work.

Btw. normal compass item in questbook shows direction to spawn point (it probably cannot be changed), so having one in inventory is usable only for getting coordinates.

**Comment by jellonek** [comment]
Detection works after shift-right clicking with compass in hand (when it gets it's first NBT), so simple solution to this task would be to only update a quest description.
