### ISSUE TITLE
Furnace Quest - Claiming the rewards greyed out

### ISSUE THREAD

**Issue by Nahkranoth0** [ChosenArchitect/Bounds-1.12-Modpack#47]
I've finished the Furnace Quest (the one for 1 furnace and 8 stone). When i try to deliver this, the options of Detect / Submit or Claim are greyed out.

I've started yesterday (02/08/2018) on version 1.1. Tried just now still on 1.3 and still nothing:
- Done the quest refresh
- Relogged couple of times
- Restarted the client
- Re-crafted the components to see if the quest was triggered

All of these steps were performed but issue still remains. Could you assist with this?

I'll attach screenshots so you can see the issue
![2018-08-03_11 13 52](https://user-images.githubusercontent.com/11743887/43637969-f5bfe0f2-970e-11e8-8980-ddce663e3420.png)
![2018-08-03_11 14 02](https://user-images.githubusercontent.com/11743887/43637973-f8996d3e-970e-11e8-85ad-9efe925e0e44.png)

**Comment by TGSRagnarok** [comment]
You need to select a reward

**Comment by Nahkranoth0** [comment]
Someone reminded me that apparently, i have to choose the reward in order for it to work.

I'll close the issue, thanks for the help!
