### ISSUE TITLE
Recipe for string to hemp please?

### ISSUE THREAD

**Issue by jelico04** [ChosenArchitect/Bounds-1.12-Modpack#53]
Thanks Chosen!

**Comment by DeadlyMitten** [comment]
are you sure you dont mean the other way around? string to hemp wouldn't really make sense in my opinion

**Comment by jelico04** [comment]
Whichever way, the goal is to make candles with hemp.

**Comment by lhdev** [comment]
Hemp needs to be grown, it would make sense to convert hemp to string but not the other way around...
