### ISSUE TITLE
Diamond pickaxe recipe in the stoked crucible needs adjusting

### ISSUE THREAD

**Issue by DrTasslehoff** [ChosenArchitect/Bounds-1.12-Modpack#57]
With the ingot cost of the pickaxe down to 2 it still breaks down into 3 ingots in the stoked crucible and giving a bonus if you were to spam craft them.

**Comment by ChosenArchitect** [comment]
Glad this is still in beta... I'll get right on a fix for that!

**Comment by DrTasslehoff** [comment]
Might be worth having all of the stoked crucible requirements act like the dungeontactics tools too, where damaged items cannot be smelted

**Comment by ChosenArchitect** [comment]
Will see if I can change
