### ISSUE TITLE
Remove Additional Structures (?)

### ISSUE THREAD

**Issue by Kaperios** [ChosenArchitect/Bounds-1.12-Modpack#67]
Leaving question mark here since it's not a big deal but you have Recurrent Complex which adds a lot more good looking structures. Also Additional Structures has Creative Commons logo in the description but it's marked as All Rights Reserved so i wouldn't really trust the mod dev as he probably doesn't know what he is doing

**Comment by ChosenArchitect** [comment]
This mod is really being used for the overworld nether portals that I made
