### ISSUE TITLE
Dirt block break model glitch

### ISSUE THREAD

**Issue by little98dime** [ChosenArchitect/Bounds-1.12-Modpack#7]
releasing the left mouse button just as a dirt block breaks results in the following graphical issue:

https://puu.sh/B3aDa/462a0e6614.png

**Comment by ChosenArchitect** [comment]
I can't repeat... I have tried as you are describing but can't get it to do it again... Is this happing a lot of just this once?

**Comment by little98dime** [comment]
After restarting, I couldn't repeat either. May have just been my instance. I'll let you know if it occurs again. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: ChosenArchitect <notifications@github.com> Date: 7/26/18  5:46 AM  (GMT-05:00) To: "ChosenArchitect/Bounds-1.12-Modpack" <Bounds-1.12-Modpack@noreply.github.com> Cc: little98dime <little98dime@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ChosenArchitect/Bounds-1.12-Modpack] Dirt block break model glitch (#7) 
I can't repeat... I have tried as you are describing but can't get it to do it again... Is this happing a lot of just this once?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ChosenArchitect/Bounds-1.12-Modpack","title":"ChosenArchitect/Bounds-1.12-Modpack","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ChosenArchitect/Bounds-1.12-Modpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ChosenArchitect in #7: I can't repeat... I have tried as you are describing but can't get it to do it again... Is this happing a lot of just this once?"}],"action":{"name":"View Issue","url":"https://github.com/ChosenArchitect/Bounds-1.12-Modpack/issues/7#issuecomment-408041552"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ChosenArchitect/Bounds-1.12-Modpack/issues/7#issuecomment-408041552",
"url": "https://github.com/ChosenArchitect/Bounds-1.12-Modpack/issues/7#issuecomment-408041552",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ChosenArchitect/Bounds-1.12-Modpack] Dirt block break model glitch (#7)",
"sections": [
{
"text": "",
"activityTitle": "**ChosenArchitect**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ChosenArchitect",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ChosenArchitect/Bounds-1.12-Modpack\",\n\"issueId\": 7,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ChosenArchitect/Bounds-1.12-Modpack\",\n\"issueId\": 7\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ChosenArchitect/Bounds-1.12-Modpack/issues/7#issuecomment-408041552"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 360979562\n}"
}
],
"themeColor": "26292E"
}
]
