### ISSUE TITLE
[Suggestion] Yoyo mod, with a few tweaks.

### ISSUE THREAD

**Issue by Fortanono** [ChosenArchitect/Bounds-1.12-Modpack#70]
The yo-yo mod is a great mod for unique weaponry and could replace the obsidian and sword based mods that you had in the pack last patch. The one tweak idea I had would be to make yoyo strings out of hemp fibers to gate them behind basic Better with Mods. (And of course, making it require the right materials.)

Link here: https://minecraft.curseforge.com/projects/yoyos

**Comment by ChosenArchitect** [comment]
Mod list is complete for now and I will not be adding any more mods to the pack at this point.
