### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kairib808** [ChosenArchitect/Bounds-1.12-Modpack#71]
Deleted beta saved. Downloaded version 2.0. Restart after doing the player's choice. Restarted just fine but now at the loading terrain screen it will show tips and then crash. Don't know what to do. Need help. Below is my crash report

Thank you

[crash-2018-08-08_00.33.16-server.txt](https://github.com/ChosenArchitect/Bounds-1.12-Modpack/files/2269944/crash-2018-08-08_00.33.16-server.txt)
n crash.

**Comment by kairib808** [comment]
[crash-2018-08-08_00.56.35-client.txt](https://github.com/ChosenArchitect/Bounds-1.12-Modpack/files/2269992/crash-2018-08-08_00.56.35-client.txt)

second crash report after removing dynamic surroundings, better foliage, and mob dismemberment

**Comment by ChosenArchitect** [comment]
Fixed in new update.
