### ISSUE TITLE
Wooden Tools Don't Lose Durability

### ISSUE THREAD

**Issue by 3AlanKing3** [ChosenArchitect/Bounds-1.12-Modpack#72]
I Just Started Last Night Playing This Modpack. The Wooden Tools At That Time Were Able To Lose Durability. This Morning, After A Recent Update, The Wooden Tools Don't Break Anymore. I'm Not Sure If This Is Supposed To Happen Or Not. I Did More Testing And It Seemed Like Stone Tools Break Faster A Lot Faster Than Before The Update. Again, I'm Not Sure If This is Part Of The Update.

**Comment by TGSRagnarok** [comment]
the same thing is happening in my world for the mudpack im working on chosen I think it may be a bug with the version of BWM that we are using

**Comment by 3AlanKing3** [comment]
Alright. Thanks for letting me know.

**Comment by ChosenArchitect** [comment]
https://gitlab.com/BetterWithMods/BetterWithMods/issues/1168 Will be fixed in the next better with mods update
