### ISSUE TITLE
Modpack hang/crash when tabbing out in fullscreen

### ISSUE THREAD

**Issue by vcnickels** [ChosenArchitect/Bounds-1.12-Modpack#74]
As stated.  Works fine in windowed mode and didn't hang/crash in previous version.

**Comment by ChosenArchitect** [comment]
I would need a crash report to see what would be causing the issue because I haven't had any problems like that.

**Comment by vcnickels** [comment]
Tried to get a log/crash report but it doesn't generate a crash...  I *think* it may be on my end as it does it on saves as well but not sure why.
