### ISSUE TITLE
Iron Ingots no longer craftable

### ISSUE THREAD

**Issue by crash19285** [ChosenArchitect/Bounds-1.12-Modpack#79]
When attempting to craft 9 iron nuggets into an iron ingot, the recipe does not work.

Crucible is the only listed way of using nuggets to smelt into an ingot, however, you need gold bars in order to craft it.  Progression in the mod pack is blocked due to this.

**Comment by ChosenArchitect** [comment]
This change was intentional.

**Comment by jeffspacito** [comment]
how do we obtain iron then?

**Comment by ChosenArchitect** [comment]
...crap lol

**Comment by ChosenArchitect** [comment]
Just pushed the new update
https://minecraft.curseforge.com/projects/bounds/files/2600676
