### ISSUE TITLE
Server console log issue

### ISSUE THREAD

**Issue by lhdev** [ChosenArchitect/Bounds-1.12-Modpack#8]
Everything works well on the server side of things, the only issue is the console is spammed with the following:

26.07 08:30:59 [Server] Server thread/INFO [betterwithmods]: BreakSpeedEvent pos: BlockPos{x=290, y=51, z=272}, state: minecraft:stone[variant=stone], held: 11xtile.dirt@0, strata: 0, speed: 1.0

Anytime someone is breaking a block, betterwithmods spams the log with those events.  Not sure if there is a config option to disable this, but it might be a good one to disable by default once you release the pack and server files.

**Comment by ChosenArchitect** [comment]
There are no config options for that.

**Comment by TGSRagnarok** [comment]
Might need to notify the mod dev on this one

**Comment by lhdev** [comment]
Opened an issue
https://gitlab.com/BetterWithMods/BetterWithMods/issues/1138

**Comment by lhdev** [comment]
According to the mod dev, it's fixed in the new 2.3.4 version
