### ISSUE TITLE
Inventory 3x3 Crafting

### ISSUE THREAD

**Issue by dmiller2606** [ChosenArchitect/Bounds-1.12-Modpack#80]
Just experienced this bug on the Bounds 2.2 server. When I hovered over a crafting table in my inventory and pressed "2" (because I wanted it in that hotbar slot) it opened up a 3x3 crafting grid that you could use normally.

**Comment by ChosenArchitect** [comment]
Its a feature but idk what mod adds that... Its not that big of a deal really and kinda nice

**Comment by ChosenArchitect** [comment]
Backpacks! mod does it... Idk why 2 set it off because it supposed to be a right click on a crafting table in your inventory.
