### ISSUE TITLE
Problems with Wild Cotton from "Plants" Mod

### ISSUE THREAD

**Issue by DeadpoolDE** [ChosenArchitect/Bounds-1.12-Modpack#81]
In Version 2.1 of the Bounds Modpack i collected a few wild cotton plants in the wild and planted them near my base. In the new Version of the Bounds Modpack ( Version 2.3) i can't harvest the wild cotton plants with right click anymore. And every other flower from the "Plants" is getting destroy if i try to collect them. Do i need now a shear to collect flowers?

**Comment by jhagrid77** [comment]
Don't smite me all mighty Chosen!

To answer your question Deadpool, yes. For almost every plant from the Plants mod you now need shears in order to collect them.

**Comment by ChosenArchitect** [comment]
You now need shears to collect them like jhagrid77 said!

**Comment by ChosenArchitect** [comment]
I will have to test for the wild cotton plants... I will have to do some testing
