### ISSUE TITLE
Why two White Candles?

### ISSUE THREAD

**Issue by vcnickels** [ChosenArchitect/Bounds-1.12-Modpack#82]
There are two White Candle recipes that aren't dictionaried, one from Better with Mods and one from Quark.  Curiously (to me anyway) the one used for the "Light the Way" quest is the one from Quark even though this is a "Better With Mods" showcase pack I believe. 

Is it possible to "ore dictionary" them or remove one?

**Comment by ChosenArchitect** [comment]
One requires zombie flesh and they can be dyed to any color

**Comment by vcnickels** [comment]
Yeah.. I see that now.  Still, a tad confusing if you aren't paying attention and trying to rush a few quests while you wait for hemp to grow.  

Is it possible to rename one to just "candle" so there is a distinction?

**Comment by ChosenArchitect** [comment]
They are really for decoration and one is larger than the other
