### ISSUE TITLE
Tree woods smelt more items than coal

### ISSUE THREAD

**Issue by DrTasslehoff** [ChosenArchitect/Bounds-1.12-Modpack#87]
Not sure if intentional but all of the base tree woods (birch, oak, etc) smelt anywhere from 12?-16 or so items. Ironwood is still around 1.5 items and I haven't checked any of the other woods but it seems odd to have implemented

**Comment by vcnickels** [comment]
I think "tiny coal" is the way to go?  Still, odd that wood (what about Charcoal?) would smealt more than Coal.
