### ISSUE TITLE
Rocket Pants bug?

### ISSUE THREAD

**Issue by vcnickels** [ChosenArchitect/Bounds-1.12-Modpack#90]
The quest item requires a Button which has been changed to an Open Blocks recipe that requires a Stone Corner and a piece of Redstone. The Stone Corner says it's deprecated but the recipe ultimately requires a Soulforged Steel Anvil which is rather involved for a Button.  There is a quest gated by it that, at least from the icon, is for the glider which can be made with tanned leather. Is that intentional or did I miss something?

Being that I'm not the type to let a button stand in the way of something like Rocket Pants (who would?) I cheated one in and the quest doesn't update. I'm not sure if that part is some savvy anti-cheat technology or the quest completion is bugged.

**Comment by ChosenArchitect** [comment]
Will fix today! Working on a update
