### ISSUE TITLE
Ore excavator issues

### ISSUE THREAD

**Issue by DelfCo** [ChosenArchitect/Bounds-1.12-Modpack#91]
I'm on the patch that was released an hour or two ago.  (Sunday, August 12)

I'm able to use ore excavator on stone, but not on iron ore. I know the release notes mentioned some changes to what could be excavated this way, but I thought it was only clay (no excavator) and logs (yes excavator). 

(Edited to add) I can't use ore excavator (the ~ key one) with a pick, on either iron ore or coal. But it when I use a Spark's Hammers Iron Hammer, it does something really weird. It appears to vein mine anything in the original 3x3x1 area, plus a bunch of stuff behind that. I'm opening up huge (4x4x4 or bigger) holes in the stone around the ore, as well as some of the ore. It's very overpowered.

**Comment by DelfCo** [comment]
Weird behavior with a hammer might be an Ore Excavator interaction with hammers. Ore excavator does something like: make a list of all ore blocks within one of the targeted ore block, then recursively add to the list all ore blocks within one of ore blocks on the list, until you've looked at all the blocks within some distance of the original target block. Then apply the tool to all the blocks on the list. I think the hammer is doing that by taking a 3x3x1 hole from each ore block on the target list instead of the usual 1x1x1, so it opens a really large, irregular area around the original ore deposit.

**Comment by DrTasslehoff** [comment]
It seems like the block blacklist isn't inverted into a whitelist. Still seems some items (clay, logs) work still while the majority of the ores still are blacklisted

**Comment by ChosenArchitect** [comment]
Will put out a patch

**Comment by DrTasslehoff** [comment]
Logs cannot be excavated still due to being named "oreLogWood" rather than just "LogWood"

**Comment by ChosenArchitect** [comment]
Patch coming out now! https://minecraft.curseforge.com/projects/bounds/files/2602774

**Comment by DelfCo** [comment]
With the patch, I can use ore excavator with a pick to get coal, iron, and logs as expected. The hammer thing is probably an issue between the ore excavator mod and the hammer mod, so it should be a separate issue from the ore excavation problem. 

I consider my original issue fixed and this bug ready to be closed. Thanks for the quick fix.
