### ISSUE TITLE
Server: Crafting Issues

### ISSUE THREAD

**Issue by carrode** [ChosenArchitect/Bounds-1.12-Modpack#93]
Hi enjoying the pack but i have an issue, created a server to play on at home for my son and i.  so when we try to craft anything that is connected to a quest (pick, axe etc) and while i can see all the recipes in JEI for the items there is no craft outcome, no error msg or anything. i can shift click ingredients into a crafting grid/table but no result.
i removed all client side mods from the server but i think i may have left out a config that is required but cannot see which one. any ideas??
Thanks.

**Comment by ChosenArchitect** [comment]
Make sure you are in using the correct version of Forge and are updated to the latest version of the pack.

**Comment by ChosenArchitect** [comment]
I don't really have anything to go off of other than that. We are running the server and have several people playing on it and haven't had that issue so I would need for info.

**Comment by carrode** [comment]
Everything is upto date (Forge and Pack) i'll try to build a new server and re-download the pack and see.
Thanks.
