### ISSUE TITLE
Openblocks auto anvil crash & Fortune enchant uncraftable

### ISSUE THREAD

**Issue by DrTasslehoff** [ChosenArchitect/Bounds-1.12-Modpack#96]
Auto-anvil crashes when you put dyes inside (any color) and essentially locks the world in a crashing loop. I'm not sure if the anvil can even get XP in this pack so might just want to disable it
Crash report: https://pastebin.com/0ic9ZQAF

The fortune enchant requires 16 lapis and according to JEI "ERR" levels. When attempting to make it it just gives a blue-text colored book rather than an enchanted one as if it doesn't register it as a valid recipe

**Comment by ChosenArchitect** [comment]
Will disable it in the next update. Seems to be an issue with quark as well. I will have to check into the fortune enchant

**Comment by ChosenArchitect** [comment]
removed in the newest update.
