### ISSUE TITLE
Dragon Does not Drop Scales

### ISSUE THREAD

**Issue by Artira421** [ChosenArchitect/Bounds-1.12-Modpack#97]
When the end dragon is summoned and killed, no dragon scales from the mod quark are dropped. Quark's website states the scale should drop on player spawned dragons and not natural spawned dragons. I suspect the EqualDragons mod is causing all player spawned dragons to be considered natural spawned dragons, preventing any dragons from ever dropping a scale.

**Comment by ChosenArchitect** [comment]
I will add the scales to the dragons drops in the next update
