### ISSUE TITLE
All saves corrupted, Inc. Backups? Shaders causing crashes?

### ISSUE THREAD

**Issue by Dublin2274** [ChosenArchitect/Bounds-1.12-Modpack#98]
Tried loading in a world after the 2.6 update and all my worlds, including backups wont load. Minecraft just stops responding and freezes.

**Comment by Dublin2274** [comment]
I have tried re installing pack and nothing. I cant even create new worlds.

**Comment by Dublin2274** [comment]
Wonderful, It was the shader pack. As soon as i disabled the shader pack (SEUS) all my worlds started loading.

**Comment by Dublin2274** [comment]
No shader packs work. Crashes game as soon as they are clicked to enable.

**Comment by ChosenArchitect** [comment]
Crash log? any more information because In my lets plays I'm using SEUS and haven't had that issue. Make sure you are getting you shaders and Optfine from the trusted source.

**Comment by ChosenArchitect** [comment]
If shaders are causing the issue then it's not a problem with the pack itself.
