### ISSUE TITLE
Problem with a bucket full of lava in normal furnace

### ISSUE THREAD

**Issue by DeadpoolDE** [ChosenArchitect/Bounds-1.12-Modpack#99]
I am playing on Bounds 2.6 and today i filled a bucket with lava to smelt some items with a normal furnace. The furnace used the lava as intended but als consumed the bucket. I tried it again in a 2.6 creative world and the furnus and pulvus are consuming the lava but not the bucket. Only the normal furnace cosumes both lava and bucket. I don't know if this a bug or works as intended.

**Comment by ChosenArchitect** [comment]
I will have to look into that because I don't believe it should be consuming the bucket.

**Comment by ChosenArchitect** [comment]
This is added by better with mods and is intended for the Hardcore furnace.
